### ISSUE TITLE
Are updates on every animation frame necessary?

### ISSUE THREAD

**Issue by mooreryan** [janestreet/bonsai#36]
Semi-repost of this question on incr_dom [here](https://github.com/janestreet/incr_dom/issues/15#issuecomment-1550859288).  Is the behavior/need to make that call on every request animation frame something fundamental to the way bonsai/incr_dom is working, or is it something that could potentially be changed/optimized?  Basically, I am wondering if the ~3% scripting/cpu usage when an bonsai app is "idle" is something that you just have to live with if you're using bonsai.  (Apologies as this is more of a question that a bug report.)

**Comment by TyOverby** [comment]
It's not fundamental to the design, and could be fixed (with some effort...) if necessary.
The reasons that the loop exists are:

1. So that time-dependent computations (like `Bonsai.Clock` functions) are automatically kept fresh
2. So that changes to `Bonsai.Var` are automatically picked up
3. So that changes to the model are automatically picked up

If we had an event-loop that integrated with those things, then it could schedule recomputes on demand.

**Comment by mooreryan** [comment]
Thanks for the info! That answers my question for now, so I will close this issue.
